services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: rick_and_morty
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
